pipeline{

    agent any

    stages{

        stage('code cloining'){

            steps{

                git clone 'https://github.com/Shrij34/Git-for-devops-workshop.git'

            }
        }
          
        }

        stage('Installing dependencies'){

            steps{

                sh npm install
            }

        }

        stage{
            steps{

                npm run test


            }
        }

        stage{
            steps{
                sh node server.js
            }
        }

}