pipeline {
    agent any

    stages {
        stage('Code Cloning') {
            steps {
                git url: 'https://github.com/Shrij34/Git-for-devops-workshop.git'
            }
        }

        stage('Installing Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'npm run test'
            }
        }

        stage('Run Node.js Server') {
            steps {
                sh 'node server.js'
            }
        }
    }
}


